### ISSUE TITLE
dicterm/main.go: faulty write of configuration key

### ISSUE THREAD

**Issue by kendfss** [murat/dicterm#3]
As it stands, the configuration is augmented by simply concatenating the key to itself whenever the user sets the key argument.

Under normal usage this seems easily avoidable, but it's a strange bug otherwise.
Perhaps it would help to do it locally, since it's a simple job for this configuration. Otherwise should use something more structured for the underlying configuration library.

**Comment by murat** [comment]
As far as I understand, you addressed to issue about opening the config file in append mode, right?

**Comment by kendfss** [comment]
yep, that's it! forgive my word salad.

**Comment by murat** [comment]
Thank you @kendfss I saw the problem. Will be fixed.
